version: "3.8"
services:
  proxy:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    restart: unless-stopped 
    ports:
      - 8191:8191
  scrapper:
    build: .
    environment:
      - PROXY=http://proxy:8191/v1
      - CHECK_INTERVAL=10s
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1023348456426835989/ihPFQ5U6M1w-yQvG-ajsn9wxshB_gc_yqcrALxkDt9m48_r7uVquo_SFVyf0Hx9p_cOA
      - ANIMEFLV_URL=https://www3.animeflv.net
      - WAIT_HOSTS=proxy:8191
    restart: unless-stopped
    depends_on:
      - proxy