version: "3.8"
services:
  proxy:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    restart: unless-stopped
#    ports:
#      - 8191:8191
  scrapper:
    build: .
    environment:
      - PROXY=http://proxy:8191/v1
      - CHECK_INTERVAL=30s
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1026627858564644935/73d-R-FiO1SfTXBVMRbaoLXV_YANTfbQuIS-WZ2uU8bv-g4GRs9ztQ1EqGChroxhZBEQ
      - ANIMEFLV_URL=https://www3.animeflv.net
      - WAIT_HOSTS=proxy:8191
    restart: unless-stopped
    depends_on:
      - proxy
